name: Build

on:
  push:
    branches: [ build ]

env:
  SOURCES: |
    src/fs-poll.c \
    src/heap-inl.h \
    src/idna.c \
    src/idna.h \
    src/inet.c \
    src/queue.h \
    src/random.c \
    src/strscpy.c \
    src/strscpy.h \
    src/threadpool.c \
    src/timer.c \
    src/uv-data-getter-setters.c \
    src/uv-common.c \
    src/uv-common.h \
    src/version.c \
    src/win/async.c \
    src/win/atomicops-inl.h \
    src/win/core.c \
    src/win/detect-wakeup.c \
    src/win/dl.c \
    src/win/error.c \
    src/win/fs-event.c \
    src/win/fs.c \
    src/win/getaddrinfo.c \
    src/win/getnameinfo.c \
    src/win/handle.c \
    src/win/handle-inl.h \
    src/win/internal.h \
    src/win/loop-watcher.c \
    src/win/pipe.c \
    src/win/poll.c \
    src/win/process-stdio.c \
    src/win/process.c \
    src/win/req-inl.h \
    src/win/signal.c \
    src/win/stream.c \
    src/win/stream-inl.h \
    src/win/tcp.c \
    src/win/thread.c \
    src/win/tty.c \
    src/win/udp.c \
    src/win/util.c \
    src/win/winapi.c \
    src/win/winapi.h \
    src/win/winsock.c \
    src/win/winsock.h


jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: build x64
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cl /c /MT -Iinclude -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 ${{ env.SOURCES }} /Folibuv.obj
        lib libuv.obj
        dir
        if not exist static mkdir static
        move /y libuv.lib static\
        cl /MT -Iinclude /D_USRDLL /D_WINDLL -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 ${{ env.SOURCES }} src\windll\dllmain.c /LD /Felibuv.dll /link
        dir
        dumpbin /dependents libuv.dll
        mkdir x64
        move static x64\
        move libuv.dll x64\
        move libuv.lib x64\

    - name: build win32
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        cl /c /MT -Iinclude -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 ${{ env.SOURCES }} /Folibuv.obj
        lib libuv.obj
        dir
        if not exist static mkdir static
        move /y libuv.lib static\
        cl /MT -Iinclude /D_USRDLL /D_WINDLL -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600 ${{ env.SOURCES }} src\windll\dllmain.c /LD /Felibuv.dll /link
        dir
        dumpbin /dependents libuv.dll
        mkdir win32
        move static win32\
        move libuv.dll win32\
        move libuv.lib win32\

    - name: list files
      shell: cmd
      run: |
        dir x64
        dir win32
        dir x64\static
        dir win32\static

    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: libuv-windows
        path: |
          x64
          win32
