name: Build

on:
  push:
    branches: [ cmake ]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Build
      shell: bash
      run: |
        mkdir -p build
        (cd build && cmake .. -DBUILD_TESTING=ON)
        cmake --build build
        # Run tests:
        (cd build && ctest -C Debug --output-on-failure)
        # Or manually run tests:
        #build/uv_run_tests                        # shared library build
        #build/uv_run_tests_a                      # static library build
