name: Build

on:
  push:
    branches: [ cmake ]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Build x64
      shell: bash
      run: |
        export ARCH="x64"
        rm -rf build
        mkdir -p build
        (cd build && cmake .. -A"x64" -DBUILD_TESTING=OFF)
        cmake --build build --config "Release" --verbose
        # list files
        ls -l build/Release
        # static library
        export dist=${ARCH}/static
        mkdir -p ${dist}
        mv build/Release/uv_a.lib  ${dist}/uv.lib
        # shared library
        mv build/Release/uv.dll ${ARCH}/
        mv build/Release/uv.lib ${ARCH}/
        # list files
        ls -l ${ARCH}/

    - name: list dependencies
      shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        dumpbin /dependents x64\uv.dll

    - name: Build x86
      if: false  # build for Windows 32-bit is disabled
      shell: bash
      run: |
        export ARCH="x86"
        rm -rf build
        mkdir -p build
        (cd build && cmake .. -A"x86" -DBUILD_TESTING=OFF)
        cmake --build build --config "Release" --verbose
        # list files
        ls -l build/Release
        # static library
        export dist=${ARCH}/static
        mkdir -p ${dist}
        mv build/Release/uv_a.lib  ${dist}/uv.lib
        # shared library
        mv build/Release/uv.dll ${ARCH}/
        mv build/Release/uv.lib ${ARCH}/
        # list files
        ls -l ${ARCH}/


    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: libuv-windows
        path: |
          x64
          #x86
