name: Build

on:
  push:
    branches: [ cmake ]

jobs:
  build:

    runs-on: windows-2016

    steps:
    - uses: actions/checkout@v2

    - name: Build x64
      shell: bash
      run: |
        export ARCH="x64"
        rm -rf build
        mkdir -p build
        (cd build && cmake .. -A"x64" -DBUILD_TESTING=OFF)
        cmake --build build --config "Release"
        # list files
        ls -l build/Release
        # static library
        export dist=${ARCH}/static
        mkdir -p ${dist}
        mv build/Release/uv_a.lib  ${dist}/uv.lib
        # shared library
        mv build/Release/uv.dll ${ARCH}/
        mv build/Release/uv.lib ${ARCH}/
        # list files
        ls -l ${ARCH}/

    - name: Build x86
      shell: bash
      run: |
        export ARCH="x86"
        rm -rf build
        mkdir -p build
        (cd build && cmake .. --config "Release" -A"x86" -DBUILD_TESTING=OFF)
        cmake --build build --config "Release"
        # list files
        ls -l build/Release
        # static library
        export dist=${ARCH}/static
        mkdir -p ${dist}
        mv build/Release/uv_a.lib  ${dist}/uv.lib
        # shared library
        mv build/Release/uv.dll ${ARCH}/
        mv build/Release/uv.lib ${ARCH}/
        # list files
        ls -l ${ARCH}/
